import React, { useState } from 'react';
import { X, Play } from 'lucide-react';
import styles from './ScriptInputModal.module.css';

interface ScriptInputModalProps {
    isOpen: boolean;
    onClose: () => void;
    onImport: (jsonString: string) => void;
}

export const ScriptInputModal: React.FC<ScriptInputModalProps> = ({ isOpen, onClose, onImport }) => {
    const [script, setScript] = useState('');
    const [error, setError] = useState<string | null>(null);

    if (!isOpen) return null;

    const handleImport = () => {
        try {
            // Basic validation
            if (!script.trim()) return;
            JSON.parse(script); // Check valid JSON
            onImport(script);
            setScript('');
            setError(null);
            onClose();
        } catch (e) {
            setError('Invalid JSON format. Please check your script.');
        }
    };

    return (
        <div className={styles.overlay}>
            <div className={styles.modal}>
                <div className={styles.header}>
                    <h3>✨ AI Script Importer</h3>
                    <button onClick={onClose} className={styles.closeBtn}><X size={18} /></button>
                </div>

                <div className={styles.content}>
                    <p className={styles.description}>
                        Paste the JSON script generated by GPT below. We'll auto-layout the nodes for you.
                    </p>
                    <textarea
                        className={styles.textarea}
                        value={script}
                        onChange={(e) => setScript(e.target.value)}
                        placeholder={'{\n  "nodes": [\n    { "type": "sysmlBlock", "label": "Engine" }\n  ],\n  "edges": []\n}'}
                    />
                    {error && <div className={styles.error}>{error}</div>}
                </div>

                <div className={styles.footer}>
                    <button onClick={onClose} className={styles.cancelBtn}>Cancel</button>
                    <button onClick={handleImport} className={styles.importBtn}>
                        <Play size={16} /> Build Diagram
                    </button>
                </div>
            </div>
        </div>
    );
};
